-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 13:43:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `con_signed` VARCHAR(2) NULL DEFAULT NULL,
  `con_date` TIMESTAMP(10) NULL DEFAULT NULL,
  `con_expiration` TIMESTAMP(10) NULL DEFAULT NULL,
  `employee_id` INT NOT NULL,
  `employee_client_id2` INT NOT NULL,
  `employee_client_id` INT NOT NULL,
  `employee_client_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_client_id2`, `employee_client_id`, `employee_client_id1`),
  UNIQUE INDEX `con_signed_UNIQUE` (`con_signed` ASC) VISIBLE,
  INDEX `fk_contract_employee1_idx` (`employee_id` ASC, `employee_client_id2` ASC, `employee_client_id` ASC, `employee_client_id1` ASC) VISIBLE,
  CONSTRAINT `fk_contract_employee1`
    FOREIGN KEY (`employee_id` , `employee_client_id2` , `employee_client_id` , `employee_client_id1`)
    REFERENCES `mydb`.`employee` (`id` , `client_id2` , `client_id` , `client_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dealer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `deal_num` INT NULL DEFAULT NULL,
  `deal_date` TIMESTAMP(10) NULL DEFAULT NULL,
  `deal_vehicle` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `deal_num_UNIQUE` (`deal_num` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_num` INT(3) NULL,
  `client_fname` VARCHAR(50) NULL,
  `client_lname` VARCHAR(50) NULL,
  `client_initial` VARCHAR(5) NULL,
  `client_address` VARCHAR(50) NULL,
  `client_contact` INT(11) NULL,
  `contract_id` INT NOT NULL,
  `dealer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `contract_id`, `dealer_id`),
  UNIQUE INDEX `client_num_UNIQUE` (`client_num` ASC) VISIBLE,
  INDEX `fk_client_contract1_idx` (`contract_id` ASC) VISIBLE,
  INDEX `fk_client_dealer1_idx` (`dealer_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_contract1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `mydb`.`contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_dealer1`
    FOREIGN KEY (`dealer_id`)
    REFERENCES `mydb`.`dealer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emp_num` INT NULL,
  `emp_fname` VARCHAR(50) NULL,
  `emp_lname` VARCHAR(50) NULL,
  `emp_initial` VARCHAR(50) NULL,
  `emp_address` VARCHAR(50) NULL,
  `emp_dob` TIMESTAMP(10) NULL,
  `client_id2` INT NOT NULL,
  `client_id` INT NOT NULL,
  `client_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id2`, `client_id`, `client_id1`),
  UNIQUE INDEX `emp_num_UNIQUE` (`emp_num` ASC) VISIBLE,
  INDEX `fk_employee_client2_idx` (`client_id2` ASC) VISIBLE,
  INDEX `fk_employee_client3_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_employee_client1_idx` (`client_id1` ASC) VISIBLE,
  CONSTRAINT `fk_employee_client2`
    FOREIGN KEY (`client_id2`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_client3`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_client1`
    FOREIGN KEY (`client_id1`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commodities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commodities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `com_num` INT(3) NULL,
  `com_type` VARCHAR(50) NULL,
  `com_validity` TIMESTAMP(10) NULL,
  `com_worth` INT(100) NULL,
  `com_quantity` INT(100) NULL,
  `com_brand` VARCHAR(50) NULL,
  `employee_id` INT NOT NULL,
  `employee_client_id1` INT NOT NULL,
  `employee_client_id2` INT NOT NULL,
  `employee_client_id` INT NOT NULL,
  `employee_id1` INT NOT NULL,
  `employee_client_id21` INT NOT NULL,
  `employee_client_id3` INT NOT NULL,
  `employee_client_id11` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_client_id1`, `employee_client_id2`, `employee_client_id`, `employee_id1`, `employee_client_id21`, `employee_client_id3`, `employee_client_id11`),
  UNIQUE INDEX `com_num_UNIQUE` (`com_num` ASC) VISIBLE,
  INDEX `fk_commodities_employee1_idx` (`employee_id` ASC, `employee_client_id1` ASC, `employee_client_id2` ASC, `employee_client_id` ASC) VISIBLE,
  INDEX `fk_commodities_employee2_idx` (`employee_id1` ASC, `employee_client_id21` ASC, `employee_client_id3` ASC, `employee_client_id11` ASC) VISIBLE,
  CONSTRAINT `fk_commodities_employee1`
    FOREIGN KEY (`employee_id` , `employee_client_id2` , `employee_client_id`)
    REFERENCES `mydb`.`employee` (`id` , `client_id2` , `client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commodities_employee2`
    FOREIGN KEY (`employee_id1` , `employee_client_id21` , `employee_client_id3` , `employee_client_id11`)
    REFERENCES `mydb`.`employee` (`id` , `client_id2` , `client_id` , `client_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`financial_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`financial_report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fr_num` INT(3) NULL DEFAULT NULL,
  `fr_amount` INT(100) NULL DEFAULT NULL,
  `fr_date` TIMESTAMP(10) NULL DEFAULT NULL,
  `employee_id` INT NOT NULL,
  `employee_client_id2` INT NOT NULL,
  `employee_client_id` INT NOT NULL,
  `employee_client_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_client_id2`, `employee_client_id`, `employee_client_id1`),
  UNIQUE INDEX `fr_num_UNIQUE` (`fr_num` ASC) VISIBLE,
  INDEX `fk_financial_report_employee1_idx` (`employee_id` ASC, `employee_client_id2` ASC, `employee_client_id` ASC, `employee_client_id1` ASC) VISIBLE,
  CONSTRAINT `fk_financial_report_employee1`
    FOREIGN KEY (`employee_id` , `employee_client_id2` , `employee_client_id` , `employee_client_id1`)
    REFERENCES `mydb`.`employee` (`id` , `client_id2` , `client_id` , `client_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sal_num` INT(3) NULL DEFAULT NULL,
  `sal_amount` INT(100) NULL DEFAULT NULL,
  `sal_received` VARCHAR(2) NULL DEFAULT NULL,
  `employee_id` INT NOT NULL,
  `employee_client_id2` INT NOT NULL,
  `employee_client_id` INT NOT NULL,
  `employee_client_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_client_id2`, `employee_client_id`, `employee_client_id1`),
  UNIQUE INDEX `sal_num_UNIQUE` (`sal_num` ASC) VISIBLE,
  INDEX `fk_salary_employee1_idx` (`employee_id` ASC, `employee_client_id2` ASC, `employee_client_id` ASC, `employee_client_id1` ASC) VISIBLE,
  CONSTRAINT `fk_salary_employee1`
    FOREIGN KEY (`employee_id` , `employee_client_id2` , `employee_client_id` , `employee_client_id1`)
    REFERENCES `mydb`.`employee` (`id` , `client_id2` , `client_id` , `client_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`training` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trai_num` INT(3) NULL DEFAULT NULL,
  `trai_location` VARCHAR(50) NULL DEFAULT NULL,
  `trai_num_employ` INT(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `trai_num_UNIQUE` (`trai_num` ASC) VISIBLE,
  UNIQUE INDEX `trai_num_employ_UNIQUE` (`trai_num_employ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`delivery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `del_id` INT(3) NULL DEFAULT NULL,
  `del_cour` VARCHAR(50) NULL DEFAULT NULL,
  `del_data_receive` VARCHAR(2) NULL DEFAULT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  UNIQUE INDEX `del_id_UNIQUE` (`del_id` ASC) VISIBLE,
  INDEX `fk_delivery_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`training_has_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`training_has_employee` (
  `training_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `employee_client_id2` INT NOT NULL,
  `employee_client_id` INT NOT NULL,
  `employee_client_id1` INT NOT NULL,
  PRIMARY KEY (`training_id`, `employee_id`, `employee_client_id2`, `employee_client_id`, `employee_client_id1`),
  INDEX `fk_training_has_employee_employee1_idx` (`employee_id` ASC, `employee_client_id2` ASC, `employee_client_id` ASC, `employee_client_id1` ASC) VISIBLE,
  INDEX `fk_training_has_employee_training1_idx` (`training_id` ASC) VISIBLE,
  CONSTRAINT `fk_training_has_employee_training1`
    FOREIGN KEY (`training_id`)
    REFERENCES `mydb`.`training` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_training_has_employee_employee1`
    FOREIGN KEY (`employee_id` , `employee_client_id2` , `employee_client_id` , `employee_client_id1`)
    REFERENCES `mydb`.`employee` (`id` , `client_id2` , `client_id` , `client_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comp_num` INT NULL DEFAULT NULL,
  `comp_foundation` VARCHAR(45) NULL DEFAULT NULL,
  `comp_site` VARCHAR(45) NULL DEFAULT NULL,
  `comp_type` VARCHAR(45) NULL DEFAULT NULL,
  `client_id` INT NOT NULL,
  `client_contract_id` INT NOT NULL,
  `client_dealer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`, `client_contract_id`, `client_dealer_id`),
  UNIQUE INDEX `comp_num_UNIQUE` (`comp_num` ASC) VISIBLE,
  INDEX `fk_company_client1_idx` (`client_id` ASC, `client_contract_id` ASC, `client_dealer_id` ASC) VISIBLE,
  CONSTRAINT `fk_company_client1`
    FOREIGN KEY (`client_id` , `client_contract_id` , `client_dealer_id`)
    REFERENCES `mydb`.`client` (`id` , `contract_id` , `dealer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prod_num` INT NULL DEFAULT NULL,
  `prod_exp_date` TIMESTAMP(10) NULL DEFAULT NULL,
  `prod_manufac` VARCHAR(45) NULL DEFAULT NULL,
  `prod_ingredient` VARCHAR(45) NULL DEFAULT NULL,
  `commodities_id` INT NOT NULL,
  `commodities_employee_id` INT NOT NULL,
  `commodities_employee_client_id1` INT NOT NULL,
  `commodities_employee_client_id2` INT NOT NULL,
  `commodities_employee_client_id` INT NOT NULL,
  `commodities_employee_id1` INT NOT NULL,
  `commodities_employee_client_id21` INT NOT NULL,
  `commodities_employee_client_id3` INT NOT NULL,
  `commodities_employee_client_id11` INT NOT NULL,
  PRIMARY KEY (`id`, `commodities_id`, `commodities_employee_id`, `commodities_employee_client_id1`, `commodities_employee_client_id2`, `commodities_employee_client_id`, `commodities_employee_id1`, `commodities_employee_client_id21`, `commodities_employee_client_id3`, `commodities_employee_client_id11`),
  UNIQUE INDEX `prod_num_UNIQUE` (`prod_num` ASC) VISIBLE,
  INDEX `fk_products_commodities1_idx` (`commodities_id` ASC, `commodities_employee_id` ASC, `commodities_employee_client_id1` ASC, `commodities_employee_client_id2` ASC, `commodities_employee_client_id` ASC, `commodities_employee_id1` ASC, `commodities_employee_client_id21` ASC, `commodities_employee_client_id3` ASC, `commodities_employee_client_id11` ASC) VISIBLE,
  CONSTRAINT `fk_products_commodities1`
    FOREIGN KEY (`commodities_id` , `commodities_employee_id` , `commodities_employee_client_id1` , `commodities_employee_client_id2` , `commodities_employee_client_id` , `commodities_employee_id1` , `commodities_employee_client_id21` , `commodities_employee_client_id3` , `commodities_employee_client_id11`)
    REFERENCES `mydb`.`commodities` (`id` , `employee_id` , `employee_client_id1` , `employee_client_id2` , `employee_client_id` , `employee_id1` , `employee_client_id21` , `employee_client_id3` , `employee_client_id11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `serv_num` VARCHAR(45) NULL DEFAULT NULL,
  `serv_dats` TIMESTAMP(10) NULL DEFAULT NULL,
  `serv_no_of_men` INT NULL DEFAULT NULL,
  `commodities_id` INT NOT NULL,
  `commodities_employee_id` INT NOT NULL,
  `commodities_employee_client_id1` INT NOT NULL,
  `commodities_employee_client_id2` INT NOT NULL,
  `commodities_employee_client_id` INT NOT NULL,
  `commodities_employee_id1` INT NOT NULL,
  `commodities_employee_client_id21` INT NOT NULL,
  `commodities_employee_client_id3` INT NOT NULL,
  `commodities_employee_client_id11` INT NOT NULL,
  PRIMARY KEY (`id`, `commodities_id`, `commodities_employee_id`, `commodities_employee_client_id1`, `commodities_employee_client_id2`, `commodities_employee_client_id`, `commodities_employee_id1`, `commodities_employee_client_id21`, `commodities_employee_client_id3`, `commodities_employee_client_id11`),
  UNIQUE INDEX `serv_num_UNIQUE` (`serv_num` ASC) VISIBLE,
  INDEX `fk_services_commodities1_idx` (`commodities_id` ASC, `commodities_employee_id` ASC, `commodities_employee_client_id1` ASC, `commodities_employee_client_id2` ASC, `commodities_employee_client_id` ASC, `commodities_employee_id1` ASC, `commodities_employee_client_id21` ASC, `commodities_employee_client_id3` ASC, `commodities_employee_client_id11` ASC) VISIBLE,
  CONSTRAINT `fk_services_commodities1`
    FOREIGN KEY (`commodities_id` , `commodities_employee_id` , `commodities_employee_client_id1` , `commodities_employee_client_id2` , `commodities_employee_client_id` , `commodities_employee_id1` , `commodities_employee_client_id21` , `commodities_employee_client_id3` , `commodities_employee_client_id11`)
    REFERENCES `mydb`.`commodities` (`id` , `employee_id` , `employee_client_id1` , `employee_client_id2` , `employee_client_id` , `employee_id1` , `employee_client_id21` , `employee_client_id3` , `employee_client_id11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_manager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prod_num` INT(3) NULL DEFAULT NULL,
  `pm_degree` VARCHAR(100) NULL DEFAULT NULL,
  `pm_trai` VARCHAR(100) NULL DEFAULT NULL,
  `pm_mas_deg` VARCHAR(100) NULL DEFAULT NULL,
  `employee_id` INT NOT NULL,
  `employee_client_id2` INT NOT NULL,
  `employee_client_id` INT NOT NULL,
  `employee_client_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_client_id2`, `employee_client_id`, `employee_client_id1`),
  UNIQUE INDEX `prod_num_UNIQUE` (`prod_num` ASC) VISIBLE,
  INDEX `fk_product_manager_employee1_idx` (`employee_id` ASC, `employee_client_id2` ASC, `employee_client_id` ASC, `employee_client_id1` ASC) VISIBLE,
  CONSTRAINT `fk_product_manager_employee1`
    FOREIGN KEY (`employee_id` , `employee_client_id2` , `employee_client_id` , `employee_client_id1`)
    REFERENCES `mydb`.`employee` (`id` , `client_id2` , `client_id` , `client_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cour_num` INT(3) NULL DEFAULT NULL,
  `cour_type` VARCHAR(45) NULL DEFAULT NULL,
  `cour_comp` VARCHAR(45) NULL DEFAULT NULL,
  `employee_id` INT NOT NULL,
  `employee_client_id2` INT NOT NULL,
  `employee_client_id` INT NOT NULL,
  `employee_client_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_client_id2`, `employee_client_id`, `employee_client_id1`),
  UNIQUE INDEX `cour_num_UNIQUE` (`cour_num` ASC) VISIBLE,
  INDEX `fk_courier_employee1_idx` (`employee_id` ASC, `employee_client_id2` ASC, `employee_client_id` ASC, `employee_client_id1` ASC) VISIBLE,
  CONSTRAINT `fk_courier_employee1`
    FOREIGN KEY (`employee_id` , `employee_client_id2` , `employee_client_id` , `employee_client_id1`)
    REFERENCES `mydb`.`employee` (`id` , `client_id2` , `client_id` , `client_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`finance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`finance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fin_num` INT(5) NULL DEFAULT NULL,
  `fin_floor` VARCHAR(45) NULL DEFAULT NULL,
  `fin_year` YEAR(4) NULL DEFAULT NULL,
  `fin_try` VARCHAR(45) NULL DEFAULT NULL,
  `employee_id` INT NOT NULL,
  `employee_client_id2` INT NOT NULL,
  `employee_client_id` INT NOT NULL,
  `employee_client_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_client_id2`, `employee_client_id`, `employee_client_id1`),
  UNIQUE INDEX `fin_num_UNIQUE` (`fin_num` ASC) VISIBLE,
  INDEX `fk_finance_employee1_idx` (`employee_id` ASC, `employee_client_id2` ASC, `employee_client_id` ASC, `employee_client_id1` ASC) VISIBLE,
  CONSTRAINT `fk_finance_employee1`
    FOREIGN KEY (`employee_id` , `employee_client_id2` , `employee_client_id` , `employee_client_id1`)
    REFERENCES `mydb`.`employee` (`id` , `client_id2` , `client_id` , `client_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
