-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 13:27:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`product_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_manager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prod_num` INT(3) NULL,
  `pm_degree` VARCHAR(100) NULL,
  `pm_trai` VARCHAR(100) NULL,
  `pm_mas_deg` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `prod_num_UNIQUE` (`prod_num` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cour_num` INT(3) NULL,
  `cour_type` VARCHAR(45) NULL,
  `cour_comp` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cour_num_UNIQUE` (`cour_num` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`finance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`finance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fin_num` INT(5) NULL,
  `fin_floor` VARCHAR(45) NULL,
  `fin_year` YEAR(4) NULL,
  `fin_try` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fin_num_UNIQUE` (`fin_num` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prod_num` INT(5) NULL,
  `prod_exp_date` TIMESTAMP(6) NULL,
  `prod_manufac` VARCHAR(50) NULL,
  `prod_ingredient` VARCHAR(100) NULL,
  `productscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `prod_num_UNIQUE` (`prod_num` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `serv_num` INT(5) NULL,
  `serv_days` VARCHAR(100) NULL,
  `serv_no_of_men` INT(3) NULL,
  `serv_availability` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `serv_num_UNIQUE` (`serv_num` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
