-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 14:39:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sal_num` INT(3) NULL,
  `sal_amount` INT(100) NULL,
  `sal_received` VARCHAR(2) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sal_num_UNIQUE` (`sal_num` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`training` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trai_num` INT(3) NULL,
  `trai_location` VARCHAR(50) NULL,
  `trai_num_employ` INT(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `trai_num_UNIQUE` (`trai_num` ASC) VISIBLE,
  UNIQUE INDEX `trai_num_employ_UNIQUE` (`trai_num_employ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`delivery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `del_id` INT(3) NULL,
  `del_cour` VARCHAR(50) NULL,
  `del_data_receive` VARCHAR(2) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `del_id_UNIQUE` (`del_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
